@extends('layouts.admin')
@section('content')
@php($state = $presentation->importStatus($run->status))
<x-admin.page-header :title="$title" :description="$description" />
@if(session('status'))<div class="mt-4 rounded border p-3 text-sm">{{ session('status') }}</div>@endif

<div class="mt-6 grid gap-6 xl:grid-cols-[1fr_.8fr]" data-admin-section="import-detail">
<x-ui.card><div class="p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-slate-500">{{ $run->provider?->name ?? 'Nguồn không xác định' }}</p><h2 class="mt-1 text-xl font-bold">{{ $presentation->operation($run->operation) }}</h2></div><x-ui.badge :variant="$state['tone']">{{ $state['label'] }}</x-ui.badge></div><dl class="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Bắt đầu</dt><dd>{{ $run->started_at?->format('d/m/Y H:i:s') ?? 'Chưa bắt đầu' }}</dd></div><div><dt class="text-slate-500">Hoàn tất</dt><dd>{{ $run->finished_at?->format('d/m/Y H:i:s') ?? 'Chưa hoàn tất' }}</dd></div><div><dt class="text-slate-500">Số lần thử</dt><dd>{{ $run->attempts }}</dd></div><div><dt class="text-slate-500">Thử lại sau</dt><dd>{{ $run->resume_after?->format('d/m/Y H:i:s') ?? '—' }}</dd></div><div><dt class="text-slate-500">Mục đã ghi nhận</dt><dd>{{ number_format($items->total()) }}</dd></div></dl>@if($run->error_summary)<div class="mt-5 rounded border border-amber-200 bg-amber-50 p-4 text-sm"><strong>Vấn đề gần nhất</strong><p class="mt-1">{{ $run->error_summary }}</p></div>@endif</div></x-ui.card>

@can('manage-providers')<x-ui.card><div class="p-5"><h2 class="font-semibold">Khôi phục tác vụ</h2><p class="mt-1 text-sm text-slate-500">Chọn hành động phù hợp với trạng thái hiện tại. Hệ thống giữ lại lịch sử trước và sau thao tác.</p><form class="mt-4 space-y-3" method="POST" action="{{ route('admin.imports.recover',$run) }}">@csrf<select name="action" class="w-full rounded border p-2"><option value="retry">Thử lại</option><option value="resume">Tiếp tục từ điểm đã lưu</option><option value="cancel">Dừng tiến trình</option></select><label class="block text-sm font-medium">Lý do thao tác<input name="rationale" required minlength="10" maxlength="2000" class="mt-1 w-full rounded border p-2" placeholder="Mô tả lý do hoặc tình huống cần xử lý"></label><input type="hidden" name="idempotency_key" value="{{ (string) str()->uuid() }}"><button class="rounded border px-4 py-2 font-semibold">Xác nhận</button></form></div></x-ui.card>@endcan
</div>

<div class="mt-6 grid gap-6 lg:grid-cols-2"><x-ui.card><div class="p-5"><h2 class="font-semibold">Vấn đề cần chú ý</h2>@forelse($failures as $failure)<div class="mt-3 rounded border p-3 text-sm"><strong>{{ $failure->message }}</strong><div class="mt-1 text-xs text-slate-500">{{ $failure->retryable ? 'Có thể thử lại' : 'Cần kiểm tra thủ công' }} · {{ $failure->error_code ? 'HTTP '.$failure->error_code.' · ' : '' }}{{ $failure->occurred_at?->format('d/m/Y H:i:s') ?? '' }}@if(data_get($failure->context, 'retry_after_seconds')) · retry sau {{ data_get($failure->context, 'retry_after_seconds') }}s @endif</div></div>@empty<p class="mt-3 text-sm text-slate-500">Không có lỗi được ghi nhận.</p>@endforelse</div></x-ui.card><x-ui.card><div class="p-5"><h2 class="font-semibold">Lịch sử khôi phục</h2>@forelse($operationAudits as $audit)<div class="mt-3 rounded border p-3 text-sm"><strong>{{ $presentation->recoveryAction($audit->action) }}</strong><div class="text-xs text-slate-500">{{ $audit->occurred_at }}</div><p class="mt-1">{{ $audit->rationale }}</p></div>@empty<p class="mt-3 text-sm text-slate-500">Chưa có thao tác khôi phục.</p>@endforelse</div></x-ui.card></div>

<x-ui.card class="mt-6"><div class="p-5"><h2 class="font-semibold">Dữ liệu trong tác vụ</h2><div class="mt-3 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="p-2 text-left">Dữ liệu nguồn</th><th class="p-2 text-left">Tình trạng</th><th class="p-2 text-left">Đã thử</th><th class="p-2 text-left">Đã liên kết canonical</th></tr></thead><tbody>@forelse($items as $item)<tr class="border-t"><td class="p-2">{{ $item->provider_entity_type }} · {{ $item->provider_entity_id }}</td><td class="p-2">{{ $item->status->value }}</td><td class="p-2">{{ $item->attempts }}</td><td class="p-2">{{ $item->canonical_entity_id ? 'Có' : 'Chưa' }}</td></tr>@empty<tr><td colspan="4" class="p-4 text-slate-500">Chưa có dữ liệu.</td></tr>@endforelse</tbody></table></div>{{ $items->links() }}</div></x-ui.card>

<details class="mt-6 rounded-xl border border-slate-200 bg-white p-5" data-admin-technical-details><summary class="cursor-pointer font-semibold">Chi tiết kỹ thuật</summary><div class="mt-5 grid gap-6 lg:grid-cols-2"><div><h3 class="font-semibold">Checkpoints</h3>@forelse($checkpoints as $checkpoint)<div class="mt-2 rounded border p-3 text-sm"><strong>{{ $checkpoint->checkpoint_key }}</strong><div class="text-xs text-slate-500">{{ $checkpoint->committed_at ?? '—' }}</div></div>@empty<p class="mt-2 text-sm text-slate-500">Không có checkpoint.</p>@endforelse</div><div><h3 class="font-semibold">HTTP request ledger</h3>@forelse($requests as $request)<div class="mt-2 rounded border p-3 text-sm">#{{ $request->sequence }} · {{ $request->method }} · HTTP {{ $request->response_status ?? '—' }}<div class="truncate text-xs text-slate-500">{{ $request->endpoint }}</div></div>@empty<p class="mt-2 text-sm text-slate-500">Không có request ledger.</p>@endforelse</div></div></details>
@endsection
