@extends('layouts.admin')
@section('content')
<x-admin.page-header :title="$title" :description="$description" />
@include('admin.operations._metrics')

<x-ui.card class="mt-6"><div class="p-4"><form method="get" class="grid gap-3 md:grid-cols-4" data-admin-section="identity-conflict-filters"><label class="text-sm">Tình trạng<select name="status" class="mt-1 w-full rounded border-slate-300 bg-transparent"><option value="">Tất cả</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected($filters['status'] === $status)>{{ ['open'=>'Cần xử lý','deferred'=>'Tạm hoãn','resolved'=>'Đã xử lý'][$status] ?? ucfirst($status) }}</option>@endforeach</select></label><label class="text-sm">Loại dữ liệu<select name="entity_type" class="mt-1 w-full rounded border-slate-300 bg-transparent"><option value="">Tất cả</option>@foreach($entityTypes as $type)<option value="{{ $type->value }}" @selected($filters['entity_type'] === $type->value)>{{ $type->label() }}</option>@endforeach</select></label><label class="text-sm">Nguồn dữ liệu<input name="provider" value="{{ $filters['provider'] }}" class="mt-1 w-full rounded border-slate-300 bg-transparent" placeholder="Ví dụ: musicbrainz" /></label><div class="flex items-end gap-2"><button class="rounded border px-4 py-2 text-sm font-semibold">Lọc</button><a href="{{ route('admin.identity-conflicts.index') }}" class="px-3 py-2 text-sm">Đặt lại</a></div></form></div></x-ui.card>

<section class="mt-6" data-admin-section="identity-conflicts"><x-ui.card><div class="p-4"><h2 class="font-semibold">Các trường hợp cần quyết định</h2><p class="mt-1 text-sm text-slate-500">Mỗi mục đại diện cho một nguồn dữ liệu có nhiều ứng viên canonical phù hợp và cần người quản trị xác nhận.</p></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr class="border-b"><th class="p-3">Nguồn & mã ngoài</th><th class="p-3">Loại</th><th class="p-3">Tình trạng</th><th class="p-3">Ứng viên</th><th class="p-3">Lịch sử quyết định</th><th class="p-3">Mở từ</th><th class="p-3"></th></tr></thead><tbody class="divide-y">@forelse($reviews as $review)<tr><td class="p-3 font-semibold">{{ $review->providerEntity?->provider?->name ?? 'Không xác định' }}<div class="text-xs text-slate-500">{{ $review->providerEntity?->external_id }}</div></td><td class="p-3">{{ $review->entity_type->label() }}</td><td class="p-3">{{ ['open'=>'Cần xử lý','deferred'=>'Tạm hoãn','resolved'=>'Đã xử lý'][$review->status->value] ?? $review->status->value }}</td><td class="p-3">{{ count($review->candidate_entity_ids ?? []) }}</td><td class="p-3">{{ $review->decisions_count }}</td><td class="p-3">{{ $review->opened_at?->format('d/m/Y H:i') }}</td><td class="p-3"><a class="font-semibold underline" href="{{ route('admin.identity-conflicts.show', $review) }}">Rà soát</a></td></tr>@empty<tr><td colspan="7" class="p-8 text-center text-slate-500">Không có xung đột định danh phù hợp với bộ lọc hiện tại.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $reviews->links() }}</div></x-ui.card></section>
@endsection
