<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$args = array_slice($argv, 1);
$jsonOnly = in_array('--json', $args, true);
$writeSource = in_array('--write-source', $args, true);
$writeRuntime = in_array('--write', $args, true);

/** @return array<string,mixed> */
function readJsonFile(string $path): array
{
    if (! is_file($path)) {
        return [];
    }

    $decoded = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

    return is_array($decoded) ? $decoded : [];
}

function normalizedHash(string $path): ?string
{
    if (! is_file($path)) {
        return null;
    }

    $content = str_replace(["\r\n", "\r"], "\n", (string) file_get_contents($path));

    return hash('sha256', $content);
}

/** @return array<string,mixed> */
function liveWorkLease(string $root): array
{
    $run = static function (string $command) use ($root): string {
        $output = shell_exec('cd '.escapeshellarg($root).' && '.$command.' 2>/dev/null');

        return trim((string) $output);
    };

    $branch = $run('git branch --show-current');
    $head = $run('git rev-parse HEAD');
    $dirty = $run('git status --porcelain --untracked-files=all') !== '';
    $prNumber = null;
    $githubRef = (string) (getenv('GITHUB_REF') ?: '');
    if (preg_match('~^refs/pull/(\d+)/~', $githubRef, $match) === 1) {
        $prNumber = (int) $match[1];
    }

    return [
        'source' => 'git-and-github-runtime',
        'branch' => $branch !== '' ? $branch : null,
        'head_sha' => $head !== '' ? $head : null,
        'dirty' => $dirty,
        'pr_number' => $prNumber,
        'base_ref' => getenv('GITHUB_BASE_REF') ?: null,
        'head_ref' => getenv('GITHUB_HEAD_REF') ?: null,
        'resume_rule' => 'Before writing, resolve the live PR for this branch/semantic owner. Resume an existing active work lease instead of opening duplicate work.',
    ];
}

/** @param array<string,mixed> $state */
function stateMarkdown(array $state): string
{
    $stage = is_array($state['current_stage'] ?? null) ? $state['current_stage'] : [];
    $next = is_array($state['next_tranche'] ?? null) ? $state['next_tranche'] : [];
    $lines = [
        '# Generated Development State',
        '',
        '> Generated from repository machine authorities. Do not edit this file manually.',
        '',
        '## Current stage',
        '',
        '- Stage `'.($stage['id'] ?? 'unknown').' — '.($stage['title'] ?? 'unknown').'`',
        '- Status: `'.($stage['status'] ?? 'unknown').'`',
        '- Accepted through: `'.($state['accepted_through'] ?? 'unknown').'`',
        '- Task contract: `'.($stage['task_contract'] ?? 'unknown').'`',
        '',
        '## Stage progress',
        '',
    ];

    foreach (($state['stage_progress'] ?? []) as $item) {
        if (! is_array($item)) {
            continue;
        }
        $lines[] = '- `'.($item['id'] ?? '?').'` — `'.strtoupper((string) ($item['status'] ?? 'unknown')).'` — '.($item['title'] ?? '');
    }

    $lines = array_merge($lines, [
        '',
        '## Next bounded tranche',
        '',
        '- `'.($next['id'] ?? 'unknown').'` — '.($next['title'] ?? 'unknown'),
        '',
        '## Live work lease',
        '',
        'Branch, PR number, exact head SHA and verification lifecycle are volatile runtime facts. Resolve them from Git/GitHub at session start with `./songchart ai status --json`; never copy them into authored progress prose.',
        '',
        '## Device / AI handoff',
        '',
        'Any device or AI client must orient from repository machine state plus the live GitHub PR before writing. If another device has advanced the PR head, refresh and resume that exact work lease instead of continuing stale local state.',
        '',
    ]);

    return implode(PHP_EOL, $lines);
}

try {
    $planPath = $root.'/docs/project/engineering/stage-plan.json';
    $plan = readJsonFile($planPath);
    if ($plan === []) {
        throw new RuntimeException('Missing or invalid stage-plan.json.');
    }

    $sources = [
        'docs/project/engineering/stage-plan.json',
        'docs/project/engineering/project-knowledge.json',
        'docs/project/engineering/consolidation-plan.json',
        'candidate-verification.json',
    ];
    $hashes = [];
    foreach ($sources as $relative) {
        $hash = normalizedHash($root.'/'.$relative);
        if ($hash !== null) {
            $hashes[$relative] = $hash;
        }
    }
    ksort($hashes);

    $state = [
        'schema_version' => 1,
        'generated_from_repository' => true,
        'source_fingerprint' => hash('sha256', json_encode($hashes, JSON_THROW_ON_ERROR)),
        'current_stage' => $plan['current_stage'] ?? null,
        'accepted_through' => $plan['accepted_through'] ?? null,
        'stage_progress' => $plan['stage_progress'] ?? [],
        'next_tranche' => $plan['next_tranche'] ?? null,
        'work_lease_policy' => $plan['work_lease'] ?? null,
        'source_hashes' => $hashes,
    ];

    if (! $writeSource) {
        $state['live_work_lease'] = liveWorkLease($root);
    }

    if ($writeSource) {
        $directory = $root.'/docs/project/generated';
        if (! is_dir($directory)) {
            mkdir($directory, 0777, true);
        }
        file_put_contents($directory.'/development-state.json', json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).PHP_EOL);
        file_put_contents($directory.'/DEVELOPMENT_STATE.md', stateMarkdown($state));
    } elseif ($writeRuntime) {
        $directory = $root.'/storage/project-state';
        if (! is_dir($directory)) {
            mkdir($directory, 0777, true);
        }
        file_put_contents($directory.'/development-state.json', json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).PHP_EOL);
    }

    if ($jsonOnly) {
        fwrite(STDOUT, json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).PHP_EOL);
        exit(0);
    }

    $stage = is_array($state['current_stage'] ?? null) ? $state['current_stage'] : [];
    $next = is_array($state['next_tranche'] ?? null) ? $state['next_tranche'] : [];
    fwrite(STDOUT, 'SongChart Derived Project State'.PHP_EOL);
    fwrite(STDOUT, 'Stage: '.($stage['id'] ?? 'unknown').' — '.($stage['status'] ?? 'unknown').PHP_EOL);
    fwrite(STDOUT, 'Accepted through: '.($state['accepted_through'] ?? 'unknown').PHP_EOL);
    fwrite(STDOUT, 'Next tranche: '.($next['id'] ?? 'unknown').' — '.($next['title'] ?? 'unknown').PHP_EOL);
    if (isset($state['live_work_lease']) && is_array($state['live_work_lease'])) {
        $lease = $state['live_work_lease'];
        fwrite(STDOUT, 'Work lease: branch='.($lease['branch'] ?? 'unknown').' head='.substr((string) ($lease['head_sha'] ?? 'unknown'), 0, 12).' pr='.($lease['pr_number'] ?? 'n/a').' dirty='.(($lease['dirty'] ?? true) ? 'yes' : 'no').PHP_EOL);
    }
} catch (Throwable $exception) {
    fwrite(STDERR, 'Unable to build derived project state: '.$exception->getMessage().PHP_EOL);
    exit(1);
}
