<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$args = array_slice($argv, 1);
$write = in_array('--write-source', $args, true);
$jsonOnly = in_array('--json', $args, true);

function readJson(string $path): array
{
    if (! is_file($path)) {
        return [];
    }

    $decoded = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

    return is_array($decoded) ? $decoded : [];
}

function stateFromJourney(string $status): string
{
    return match (true) {
        str_contains($status, 'implemented') && ! str_contains($status, 'partial') && ! str_contains($status, 'gap') => 'implemented',
        str_contains($status, 'partial'), str_contains($status, 'gap') => 'partial',
        str_contains($status, 'planned') => 'planned',
        default => 'unknown',
    };
}

function featureMatrixMarkdown(array $index): string
{
    $lines = [
        '# Generated Feature Matrix',
        '',
        '> Generated from repository authorities. Do not edit manually.',
        '',
        '| Journey | State | Goal | Mapped use cases | Explicit gaps |',
        '| --- | --- | --- | ---: | ---: |',
    ];

    foreach ($index['journeys'] as $journey) {
        $lines[] = '| `'.$journey['id'].'` | `'.$journey['state'].'` | '.str_replace('|', '\\|', $journey['goal']).' | '.count($journey['mapped_use_cases']).' | '.count($journey['gaps']).' |';
    }

    $lines[] = '';
    $lines[] = '## Unmapped declared entrypoints';
    $lines[] = '';
    if ($index['unmapped_entrypoints'] === []) {
        $lines[] = '- None.';
    } else {
        foreach ($index['unmapped_entrypoints'] as $gap) {
            $lines[] = '- `'.$gap['journey'].'` -> `'.$gap['entrypoint'].'` — '.$gap['reason'];
        }
    }

    return implode(PHP_EOL, $lines).PHP_EOL;
}

function systemGuideMarkdown(array $index): string
{
    $p = $index['product'];
    $coverage = $index['coverage'];
    $lines = [
        '# SongChart System Guide',
        '',
        '> Generated orientation layer. Source authorities are linked in `system-knowledge.json`; do not edit this file manually.',
        '',
        '## 1. What this system is',
        '',
        $p['summary'],
        '',
        'The short mental model is: **user journey -> capability/use case -> route/implementation -> domain/data owner -> verification -> roadmap**.',
        '',
        '## 2. What exists now',
        '',
    ];

    foreach ($index['journeys'] as $journey) {
        $lines[] = '- **'.$journey['id'].'** — `'.$journey['state'].'` — '.$journey['goal'];
    }

    $lines = array_merge($lines, [
        '',
        '## 3. Coverage at a glance',
        '',
        '- Journeys: `'.$coverage['journeys'].'`',
        '- Use-case contracts: `'.$coverage['use_cases'].'`',
        '- Journey-declared use cases mapped: `'.$coverage['mapped_use_cases'].'`',
        '- Explicitly unmapped route/use-case entrypoints: `'.$coverage['unmapped_entrypoints'].'`',
        '- Current stage: `'.$index['stage']['id'].'` — '.$index['stage']['title'].' (`'.$index['stage']['status'].'`)',
        '',
        '## 4. How to trace one feature',
        '',
        '1. Start from a journey ID in `system-knowledge.json`.',
        '2. Follow its mapped use-case IDs; each record carries route, URI, implementation and data surfaces when known.',
        '3. Follow data-surface owners into schema/domain authority instead of searching table names blindly.',
        '4. Check the journey/use-case state to distinguish implemented, partial, planned and explicit gaps.',
        '5. Check current stage/roadmap before adding a new capability.',
        '',
        '## 5. Known gaps that should not be guessed around',
        '',
    ]);

    if ($index['unmapped_entrypoints'] === []) {
        $lines[] = '- No declared journey entrypoint is currently unmapped.';
    } else {
        foreach ($index['unmapped_entrypoints'] as $gap) {
            $lines[] = '- `'.$gap['journey'].'` declares `'.$gap['entrypoint'].'`, but no matching executable use-case contract is mapped yet. '.$gap['reason'];
        }
    }

    $lines = array_merge($lines, [
        '',
        '## 6. Audience projections',
        '',
        '- **New developer:** read this guide, then `FEATURE_MATRIX.md`, then open only the authorities referenced by the feature being changed.',
        '- **AI:** load `system-knowledge.json` first; resolve semantic IDs and source authorities before inspecting implementation files.',
        '- **Product owner:** focus on journey state, gaps, decision debt and roadmap; implementation paths are secondary.',
        '- **Operator:** follow operational journeys and verification/recovery authorities.',
        '- **End user:** future user guides should be generated only from implemented public capabilities and must hide internal IDs, contracts and infrastructure.',
        '',
        '## 7. Rule for future documentation',
        '',
        'Do not create an independently maintained user/dev/AI guide that copies system facts. Add or correct the owning authority/mapping, then regenerate the appropriate audience projection from this knowledge layer.',
        '',
    ]);

    return implode(PHP_EOL, $lines);
}

try {
    $contract = readJson($root.'/docs/project/engineering/system-knowledge-contract.json');
    $project = readJson($root.'/docs/project/engineering/project-knowledge.json');
    $journeys = readJson($root.'/docs/project/domain/product-user-journeys.json');
    $useCases = readJson($root.'/docs/project/domain/use-case-contracts.json');
    $stagePlan = readJson($root.'/docs/project/engineering/stage-plan.json');
    $roadmap = readJson($root.'/docs/project/engineering/roadmap.json');

    if ($contract === [] || $project === [] || $journeys === [] || $useCases === [] || $stagePlan === []) {
        throw new RuntimeException('Required system knowledge authorities are missing or invalid.');
    }

    $useCaseMap = is_array($useCases['use_cases'] ?? null) ? $useCases['use_cases'] : [];
    $journeyIndex = [];
    $unmapped = [];
    $mappedCount = 0;

    foreach (($journeys['journeys'] ?? []) as $journeyId => $journey) {
        if (! is_array($journey)) {
            continue;
        }

        $declaredUseCases = array_values(array_filter(array_map('strval', $journey['use_cases'] ?? [])));
        $routeNames = array_values(array_filter(array_map('strval', $journey['route_names'] ?? [])));
        $mapped = [];
        foreach ($declaredUseCases as $useCaseId) {
            if (isset($useCaseMap[$useCaseId]) && is_array($useCaseMap[$useCaseId])) {
                $uc = $useCaseMap[$useCaseId];
                $mapped[$useCaseId] = [
                    'id' => $useCaseId,
                    'route_name' => $uc['route_name'] ?? null,
                    'uri' => $uc['uri'] ?? null,
                    'method' => $uc['method'] ?? null,
                    'implementation' => $uc['implementation'] ?? null,
                    'read_only' => $uc['read_only'] ?? null,
                    'data_surfaces' => array_keys(array_merge(
                        is_array($uc['data_surfaces'] ?? null) ? $uc['data_surfaces'] : [],
                        is_array($uc['support_surfaces'] ?? null) ? $uc['support_surfaces'] : [],
                    )),
                    'source' => 'docs/project/domain/use-case-contracts.json#use_cases.'.$useCaseId,
                ];
                $mappedCount++;
            } else {
                $unmapped[] = [
                    'journey' => (string) $journeyId,
                    'entrypoint' => $useCaseId,
                    'reason' => 'Declared use-case ID has no executable use-case contract.',
                ];
            }
        }

        foreach ($routeNames as $routeName) {
            $found = false;
            foreach ($useCaseMap as $uc) {
                if (is_array($uc) && ($uc['route_name'] ?? null) === $routeName) {
                    $found = true;
                    break;
                }
            }
            if (! $found) {
                $unmapped[] = [
                    'journey' => (string) $journeyId,
                    'entrypoint' => $routeName,
                    'reason' => 'Journey declares this route explicitly but no use-case contract maps to it.',
                ];
            }
        }

        $journeyIndex[] = [
            'id' => (string) $journeyId,
            'actor' => $journey['actor'] ?? null,
            'status' => $journey['status'] ?? 'unknown',
            'state' => stateFromJourney((string) ($journey['status'] ?? 'unknown')),
            'goal' => (string) ($journey['goal'] ?? ''),
            'required_capabilities' => array_values(array_map('strval', $journey['required_domain_capabilities'] ?? [])),
            'mapped_use_cases' => array_values($mapped),
            'gaps' => array_values(array_map('strval', $journey['stage_20_gaps'] ?? [])),
            'source' => 'docs/project/domain/product-user-journeys.json#journeys.'.$journeyId,
        ];
    }

    $stage = is_array($stagePlan['current_stage'] ?? null) ? $stagePlan['current_stage'] : [];
    $index = [
        'schema_version' => 1,
        'generated_from_repository' => true,
        'contract' => 'docs/project/engineering/system-knowledge-contract.json',
        'product' => [
            'name' => $project['identity']['product'] ?? 'SongChart',
            'summary' => $project['identity']['product_summary'] ?? ($journeys['product_purpose'] ?? ''),
            'source' => 'docs/project/engineering/project-knowledge.json',
        ],
        'stage' => [
            'id' => $stage['id'] ?? 'unknown',
            'title' => $stage['title'] ?? 'unknown',
            'status' => $stage['status'] ?? 'unknown',
            'accepted_through' => $stagePlan['accepted_through'] ?? null,
            'source' => 'docs/project/engineering/stage-plan.json',
        ],
        'roadmap' => $roadmap,
        'journeys' => $journeyIndex,
        'use_cases' => $useCaseMap,
        'unmapped_entrypoints' => $unmapped,
        'coverage' => [
            'journeys' => count($journeyIndex),
            'use_cases' => count($useCaseMap),
            'mapped_use_cases' => $mappedCount,
            'unmapped_entrypoints' => count($unmapped),
        ],
        'source_authorities' => $contract['source_authorities'] ?? [],
        'audience_projections' => $contract['audience_projections'] ?? [],
        'navigation_rule' => 'Resolve semantic journey/use-case/capability IDs and their source authorities before searching implementation names.',
    ];

    if ($write) {
        $directory = $root.'/docs/project/generated';
        if (! is_dir($directory)) {
            mkdir($directory, 0777, true);
        }
        file_put_contents($directory.'/system-knowledge.json', json_encode($index, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).PHP_EOL);
        file_put_contents($directory.'/SYSTEM_GUIDE.md', systemGuideMarkdown($index));
        file_put_contents($directory.'/FEATURE_MATRIX.md', featureMatrixMarkdown($index));
    }

    if ($jsonOnly) {
        fwrite(STDOUT, json_encode($index, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).PHP_EOL);
        exit(0);
    }

    fwrite(STDOUT, 'SongChart System Knowledge'.PHP_EOL);
    fwrite(STDOUT, 'Journeys: '.$index['coverage']['journeys'].' Use cases: '.$index['coverage']['use_cases'].' Unmapped: '.$index['coverage']['unmapped_entrypoints'].PHP_EOL);
    fwrite(STDOUT, 'Machine JSON: php scripts/system-knowledge.php --json'.PHP_EOL);
} catch (Throwable $exception) {
    fwrite(STDERR, 'Unable to compile system knowledge: '.$exception->getMessage().PHP_EOL);
    exit(1);
}
